version: AppVeyor build {build}
shallow_clone: true
image: Ubuntu
install:
- sh: >-
    git clone https://github.com/aboood40091/SARC-Tool.git

    echo -en "\n\n" |sudo apt install python3-pip

    sudo pip3 install SarcLib

    sudo pip3 install libyaz0

build_script:
- sh: >-
    rm 01003bc0000a0000/Romfs/Message/CommonMsg_USen.release/*.lot

    rm 01003bc0000a0000/Romfs/Message/LayoutMsg_USen.release/*.lot

    python3 SARC-Tool/main.py -compress -little 01003bc0000a0000/Romfs/Message/CommonMsg_USen.release

    python3 SARC-Tool/main.py -compress -little 01003bc0000a0000/Romfs/Message/LayoutMsg_USen.release

    mkdir -p Release/Message/TitleID/Romfs/Message

    mkdir -p Release/Model/TitleID/Romfs/Model

    mkdir -p Release/OE-Model/OE-TitleID/Romfs/Model

    cp README.md Release/Message/README.md

    cp README.md Release/OE-Model/README.md

    cp README.md Release/Model/README.md

    mv 01003bc0000a0000/Romfs/Message/LayoutMsg_USen.release.szs Release/Message/TitleID/Romfs/Message/LayoutMsg_USen.release.szs

    mv 01003bc0000a0000/Romfs/Message/CommonMsg_USen.release.szs Release/Message/TitleID/Romfs/Message/CommonMsg_USen.release.szs

    mv 01003bc0000a0000/Romfs/Model Release/Model/TitleID/Romfs

    mv 01003bc0000a1065/Romfs/Model Release/OE-Model/OE-TitleID/Romfs

artifacts:
- path: Release\Message
- path: Release\Model
- path: Release\OE-Model
deploy: off
